# Site
title:              Machine Code Construction Yard
email:              georgjziegler@gmail.com
bio:                "Blog on machine code programming, vintage computer hardware, game development, and boat building. Updates on Thursdays. Please click on 'Posts'."
description:        "I do assembly programming on old machines and boat building."
future:             false
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://georgjz.github.io
# url:                http://localhost:4000 # for local debugging
baseurl:            /

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   georgsyard

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-122825347-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
# twitter:            username
# facebook:           username
github-url:         georgjz
stackoverflow:      5594534/georgjz
#instagram:          username
tumblr:             georgsyard
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel

# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
